version: "3.7"
services:
  api:
    build:
      context: "./api"
    networks:
      - ctfnote
    environment:
      CREATE_PAD_URL: "http://hedgedoc:3000/new"
      SHOW_PAD_URL: "/"
      DATABASE_URL: "postgres://ctfnote:ctfnote@db:5432/ctfnote"
    depends_on:
      - db
  db:
    build:
      context: "./db"
    restart: always
    environment:
      POSTGRES_PASSWORD: ctfnote
      POSTGRES_USER: ctfnote
      POSTGRES_MULTIPLE_DATABASES: hedgedoc
    volumes:
      - ctfnote-db:/var/lib/postgresql/data
    networks:
      - ctfnote
  front:
    networks:
      - ctfnote
    build:
      context: "./front"
    depends_on:
      - hedgedoc
    ports:
      - 80:80
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.8.2-debian
    environment:
      - CMD_DB_URL=postgres://ctfnote:ctfnote@db:5432/hedgedoc
      - CMD_URL_PATH=pad
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
    depends_on:
      - db
    restart: always
    volumes:
      - pad-uploads:/home/hackmd/app/public/uploads
    networks:
      - ctfnote
volumes:
  ctfnote-db:
  pad-uploads:
networks:
  ctfnote:
