name: "Build and push Docker images"

on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ github.token }}
            - name: PrepareReg Names
              run: |
                  echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
                  echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: ./front
                  push: true
                  tags: ghcr.io/${{env.IMAGE_REPOSITORY}}/front:latest
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: ./api
                  push: true
                  tags: ghcr.io/${{env.IMAGE_REPOSITORY}}/api:latest
